[package]
name = "api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" } # depends on your needs
poem = "3.0.0"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
futures = "0.3.30"
dotenvy = "0.15.7"
chrono = "0.4.38"
